### ISSUE TITLE
多音字怎么办啊

### ISSUE THREAD

**Issue by wheretakenlu** [bjzhangyang/ZYPinYinSearch#1]
长沙，长春这些都分到Z了，估计是成了zhang，怎么办呢？

**Comment by bjzhangyang** [comment]
[ZYPinYinSearch setupReplacement:^NSDictionary *{
return @{@"长春":@"changchun",@"重庆":@"chongqing"};//长春默认是"zhangchun"，所以这里可以特殊设置成"changchun"
}];
